/**
 * GENERATED FILE — do not edit by hand.
 * Source: branding.json · Regenerated by `bun run gen:branding`
 */
import type { Branding } from "./branding.types";

export const branding = {
  displayName: "My App",
  shortName: "My App",
  npmScope: "@acme",
  publicOrigin: "https://www.example.com",
  supportEmail: "support@example.com",
  legalName: "My App",
} as const satisfies Branding;

export type { Branding };
