import type { Branding } from "./branding.types";
import { BRANDING_KEYS } from "./branding.types";

export type { Branding };

export function assertBranding(value: unknown): Branding {
  if (value === null || typeof value !== "object") {
    throw new Error("branding.json must be an object");
  }
  const record = value as Record<string, unknown>;
  const missing = BRANDING_KEYS.filter((key) => {
    const v = record[key];
    return typeof v !== "string" || v.trim().length === 0;
  });
  if (missing.length > 0) {
    throw new Error(`branding.json missing or empty keys: ${missing.join(", ")}`);
  }
  const npmScope = record.npmScope as string;
  if (!npmScope.startsWith("@") || npmScope.includes("/")) {
    throw new Error('branding.npmScope must look like "@acme" (no slash)');
  }
  return {
    displayName: record.displayName as string,
    shortName: record.shortName as string,
    npmScope,
    publicOrigin: record.publicOrigin as string,
    supportEmail: record.supportEmail as string,
    legalName: record.legalName as string,
  };
}

export function renderBrandingModule(branding: Branding): string {
  const body = BRANDING_KEYS.map((key) => `  ${key}: ${JSON.stringify(branding[key])},`).join("\n");
  return `/**
 * GENERATED FILE — do not edit by hand.
 * Source: branding.json · Regenerated by \`bun run gen:branding\`
 */
import type { Branding } from "./branding.types";

export const branding = {
${body}
} as const satisfies Branding;

export type { Branding };
`;
}

export function formatEmailFrom(legalOrDisplayName: string, address: string): string {
  return `${legalOrDisplayName} <${address}>`;
}

export function slugFromNpmScope(npmScope: string): string {
  return npmScope.startsWith("@") ? npmScope.slice(1) : npmScope;
}
